server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/campus_placement}
      database: campus_placement
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:4C7ZvkSWhc0upMVkRLunfh4o0flMOvyqNzEByNBST1g+8fDJtyCwXqoUVO7sEdArGsqYC61NdmOiE/p8xOnAfQ==}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:placeholder}
  api-key: ${CLOUDINARY_API_KEY:placeholder}
  api-secret: ${CLOUDINARY_API_SECRET:placeholder}

logging:
  level:
    com.placement: DEBUG
